version: "3.1"

services:
  tgbot:
    container_name: cheapest-service-bot
    build:
      context: .
      dockerfile: Dockerfile
    command: python app.py
    restart: always
    env_file:
      - .env
    volumes:
      - .:/src
    depends_on:
      - redis
    networks:
      - tg_bot

  redis:
    container_name: "${REDIS_CONTAINER_NAME:-redis-container}"
    image: redis:alpine
    command: "redis-server --requirepass ${REDIS_PASS:-password123}"
    restart: always
    networks:
      - tg_bot
    volumes:
      - ./redis:/data

networks:
  tg_bot:
    driver: bridge