from .services import services_callback_data, services_keyboard, services_delete_keyboard, services_cancel_keyboard, services_edit_keyboard
from .categories import categories_callback_data, categories_keyboard, categories_delete_keyboard, categories_cancel_keyboard, categories_edit_keyboard
from .numbers import numbers_callback_data, numbers_keyboard, numbers_delete_keyboard, numbers_cancel_keyboard, numbers_edit_keyboard, delete_number_keyboard
